# Generated by Django 6.0.1 on 2026-06-30 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0002_alter_savingsdeposit_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsdeposit',
            name='transaction_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The actual date of the transaction', null=True),
        ),
    ]
