# Generated by Django 6.0.1 on 2026-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
