# Generated by Django 6.0.1 on 2026-06-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalbatches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalbatch',
            options={'ordering': ['-posting_date'], 'verbose_name': 'Journal Batch', 'verbose_name_plural': 'Journal Batches'},
        ),
    ]
