# Generated by Django 6.0.1 on 2026-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_employment_type_user_payroll_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
