# Generated by Django 6.0.1 on 2026-04-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ventureaccounts", "0001_initial"),
        ("venturetypes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventureaccount",
            name="venture_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="venturetypes.venturetype",
            ),
        ),
    ]
