# Generated by Django 6.0.1 on 2026-06-30 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandisbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandisbursement',
            name='transaction_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The actual date of the transaction', null=True),
        ),
    ]
