# Generated by Django 6.0.1 on 2026-06-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feepayments', '0002_alter_feepayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='notes',
            field=models.TextField(blank=True, help_text='Used to explain why a fee is exceeded i.e share capital transfer', null=True),
        ),
    ]
