# Generated by Django 6.0.1 on 2026-04-18 13:30

import loanaccounts.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('account_number', models.CharField(default=loanaccounts.utils.generate_loan_account_number, max_length=20, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_interest_calulation', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Funded', 'Funded'), ('Closed', 'Closed'), ('Defaulted', 'Defaulted')], default='Active', max_length=20)),
                ('total_interest_accrued', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projection_snapshot', models.JSONField(blank=True, default=dict, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Loan Account',
                'verbose_name_plural': 'Loan Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
