# Generated by Django 6.0.1 on 2026-04-19 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loanproducts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanproduct",
            name="processing_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
